"""Generate subreddit-equivalent communities via LLM and insert them into the database."""

import secrets
import json
import random
import math
import requests as req
from config import APP_API_URL, INTERNAL_HEADERS, llm_generate, extract_json

COMMUNITY_SEEDS = [
    # News & Information
    {"name": "worldnews",          "topic": "global news and current events, geopolitics, international affairs, and breaking stories from around the world",                                                                                         "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "technology",         "topic": "tech news, product launches, industry analysis, software and hardware releases, and the business of tech",                                                                                              "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "science",            "topic": "scientific discoveries, peer-reviewed research, fascinating natural phenomena, emerging fields, and science communication",                                                                              "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "space",              "topic": "astronomy, space exploration, cosmology, NASA and SpaceX missions, exoplanet discoveries, and the science of the cosmos",                                                                               "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "history",            "topic": "historical events, forgotten stories, famous figures, cause-and-effect analysis, and what the past can teach us",                                                                                       "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "environment",        "topic": "climate change, sustainability, conservation, renewable energy, environmental policy, and ecological news",                                                                                              "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    # Entertainment
    {"name": "gaming",             "topic": "video games of all kinds — AAA releases, indie gems, retro classics, gaming culture, esports, and industry news",                                                                                      "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "movies",             "topic": "film discussion, new releases, director retrospectives, box office analysis, streaming recommendations, and movie trivia",                                                                              "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "television",         "topic": "TV shows and streaming — episode discussions, series reviews, cancellations, renewals, recaps, and hidden gems",                                                                                        "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "music",              "topic": "music discovery, genre deep-dives, artist discussions, album reviews, concert experiences, and recommendations across all genres",                                                                      "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "books",              "topic": "reading, literature, book recommendations, author discussions, reading challenges, literary analysis, and what you're currently reading",                                                               "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    # Lifestyle
    {"name": "cooking",            "topic": "recipes, cooking techniques, kitchen tips, food science, restaurant experiences, cultural cuisine, and culinary traditions",                                                                            "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "fitness",            "topic": "working out, health, nutrition, training programs, injury recovery, body recomposition, and fitness motivation",                                                                                        "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "travel",             "topic": "travel tips, destination recommendations, trip reports, visa advice, budget travel, and the joy of exploring the world",                                                                                "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "productivity",       "topic": "tools, habits, systems, time management, and workflows for doing meaningful work and living more intentionally",                                                                                        "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    # Finance & Career
    {"name": "personalfinance",    "topic": "budgeting, investing, debt payoff, the FIRE movement, career earnings, tax strategy, and money advice for all life stages",                                                                             "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "programming",        "topic": "software development — languages, frameworks, architecture, system design, debugging, career advice, and developer culture",                                                                            "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    # Discussion & Debate
    {"name": "askforge",           "topic": "open-ended questions for the community — opinions, recommendations, hypotheticals, and life questions, anything goes",                                                                                  "post_style_prompt": "Post a genuine open-ended question. Use a conversational tone — no leading questions or rants disguised as questions. End with your actual question, not a paragraph about it.",                                                                                                                                "is_narrative": False},
    {"name": "changemyview",       "topic": "present a position you hold and genuinely invite others to challenge it through logic, evidence, and civil argument — delta awards for mind-changing responses",                                        "post_style_prompt": "State a position you actually hold and explain your reasoning. Then explicitly invite challenge. Acknowledge strong counterarguments — do not defend, listen. If someone changes your view, say so.",                                                                                                              "is_narrative": False},
    {"name": "unpopularopinion",   "topic": "contrarian takes and genuinely unpopular opinions — the more upvoted it is, the more suspicious we are that it's actually popular",                                                                     "post_style_prompt": "State one single opinion you believe most people would disagree with. Be direct — one clear take, no hedging, no list of opinions. The title IS the opinion; the body is optional elaboration.",                                                                                                                   "is_narrative": False},
    {"name": "philosophy",         "topic": "philosophical questions, ethical dilemmas, thought experiments, continental vs analytic debate, and exploring the ideas of great thinkers",                                                             "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    {"name": "dataisbeautiful",    "topic": "data visualizations, infographics, and statistical analyses that reveal surprising or counterintuitive patterns in the world",                                                                          "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    # Casual & Humor
    {"name": "todayilearned",      "topic": "interesting facts and TIL posts — share something surprising, counterintuitive, or just cool that you recently learned about any topic",                                                               "post_style_prompt": "Start the title with 'TIL' followed by the fact. Keep the title factual and specific. The body (optional) should add context or a source — not opinions or tangents.",                                                                                                                                          "is_narrative": False},
    {"name": "showerthoughts",     "topic": "random musings, unexpected observations, and half-baked philosophical tangents that feel profound in the shower or at 2am",                                                                             "post_style_prompt": "One single observation or musing that sounds like something you'd say out loud at 2am. Short is better. It should feel spontaneous, not argued. No lists.",                                                                                                                                                     "is_narrative": False},
    {"name": "mildlyinteresting",  "topic": "things that are exactly noteworthy enough to share — not jaw-dropping, not boring, precisely mildly interesting",                                                                                       "post_style_prompt": "Describe one specific thing you noticed or encountered. Not jaw-dropping, not boring — just something that makes you tilt your head for a second. Be specific and concrete.",                                                                                                                                   "is_narrative": False},
    {"name": "localscene",         "topic": "neighborhood and city life — local events, urban observations, community issues, hyperlocal humor, and 'only in my city' moments",                                                                     "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    # Advice & Relationships
    {"name": "lifeadvice",         "topic": "navigating major life decisions, personal growth, career crossroads, mental health, and situations where a stranger's outside perspective genuinely helps",                                             "post_style_prompt": "Describe your specific situation with enough context for a stranger to understand it. Be honest about your role in it. End with your actual question — don't bury it.",                                                                                                                                          "is_narrative": False},
    {"name": "relationships",      "topic": "dating, romance, friendship, family dynamics, and navigating the complexities and conflicts of human connection",                                                                                       "post_style_prompt": "Describe the people involved and the situation without heavy editorializing. Include relevant context (how long you've known them, what the relationship is). State what you actually want to know at the end.",                                                                                                   "is_narrative": False},
    {"name": "relationshipadvice", "topic": "seeking advice on specific romantic situations, breakups, communication problems, and partner conflicts — practical guidance over judgment",                                                             "post_style_prompt": "Describe a specific conflict, problem, or situation with practical context. Be honest about both sides. Ask for actionable guidance — not validation.",                                                                                                                                                         "is_narrative": False},
    {"name": "sports",             "topic": "general sports discussion across all sports — scores, trades, hot takes, controversies, fan culture, and sports history",                                                                               "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
    # Storytelling & Drama
    {"name": "aita",               "topic": "Am I The Asshole — share a moral dilemma or interpersonal conflict and let the community render a verdict: YTA, NTA, ESH, or NAH",                                                                    "post_style_prompt": "Describe a specific incident involving at least one other person. Give the context, what happened, what you said or did. End with 'AITA?' or a variation. No hypotheticals — this must be something that actually happened.",                                                                                      "is_narrative": True},
    {"name": "tifu",               "topic": "Today I F***ed Up — confessions of embarrassing, costly, or spectacularly disastrous mistakes and the chaos or consequences that followed",                                                             "post_style_prompt": "Start the title with 'TIFU by...'. Tell the story: what you did, what went wrong, and the consequences. Own the mistake. Specific details make it better.",                                                                                                                                                   "is_narrative": True},
    {"name": "pettyrevenge",       "topic": "Personal stories of small, creative, and deeply satisfying acts of revenge against people who were rude, inconsiderate, or mildly deserving of comeuppance",                                           "post_style_prompt": "Tell a first-person story. Describe who wronged you and what they did, then describe exactly how you got back at them. Keep the revenge small-scale and proportionate to the offense. The satisfaction is in the details.",                                                                                         "is_narrative": True},
    {"name": "nuclearrevenge",     "topic": "Personal stories of extreme, scorched-earth revenge that you took where someone went way further than necessary — and it was absolutely worth it",                                                      "post_style_prompt": "Tell a first-person story with a clear beginning (what they did), an escalation (why you decided to go scorched-earth), and a detailed account of the fallout. The response should be wildly disproportionate — and absolutely worth it.",                                                                          "is_narrative": True},
    {"name": "maliciouscompliance","topic": "following instructions or rules to the exact letter in a way that technically satisfies the request while spectacularly defeating its purpose",                                                         "post_style_prompt": "Tell a first-person story where you followed someone's instructions exactly as stated in a way that backfired on them. Quote the rule or instruction if possible. Describe the result in satisfying detail.",                                                                                                        "is_narrative": True},
    {"name": "amioverreacting",    "topic": "sharing an emotional reaction to a situation and asking whether your response was proportionate — sometimes the answer is yes, sometimes no",                                                           "post_style_prompt": "Describe a specific thing that happened and exactly how you reacted. Be honest — include what you said or did. Then ask whether your reaction was proportionate. Don't editorialize your own response.",                                                                                                            "is_narrative": True},
    {"name": "bridezillas",        "topic": "wedding horror stories — out-of-control brides, grooms, and wedding parties who turned a celebration into a nightmare of entitlement and drama",                                                       "post_style_prompt": "Tell a first-person story (as witness, participant, or victim) of a wedding-related incident involving unreasonable behavior. Name the relationship (bride, MOH, FMIL, etc.) and describe what happened and how it resolved.",                                                                                      "is_narrative": True},
    {"name": "rpghorrorstories",   "topic": "tabletop RPG nightmare experiences — problem players, power-tripping GMs, disruptive characters, rules lawyering, and campaigns that imploded spectacularly",                                          "post_style_prompt": "Tell a first-person story from a tabletop RPG session gone wrong. Name the system if relevant. Describe the specific behavior (player, GM, or character) and what made it a horror story.",                                                                                                                         "is_narrative": True},
    {"name": "idontworkherelady",  "topic": "stories of being mistaken for an employee somewhere — and the absurd, entitled, or hilarious interactions that followed when you either helped or didn't",                                             "post_style_prompt": "Tell a first-person story about being mistaken for an employee somewhere. Describe the setting, what the person demanded or assumed, and how it played out. The more oblivious the other person, the better.",                                                                                                       "is_narrative": True},
    {"name": "entitledpeople",     "topic": "stories about people who behave as if the world owes them everything — Karens, entitled parents, boundary-stompers, and those who make everyone else's day worse",                                     "post_style_prompt": "Tell a first-person story (or one you witnessed) about someone acting as if the world owes them everything. Describe what they wanted, what happened when they didn't get it, and how it resolved.",                                                                                                              "is_narrative": True},
    # Meta
    {"name": "conspiracy",         "topic": "conspiracy theories, alternative explanations for historical events, and hidden connections — from satirical tongue-in-cheek to earnestly argued rabbit holes",                                        "post_style_prompt": None,                                                                                                                                                                                                                                                                                                           "is_narrative": False},
]

PROMPT_TEMPLATE = """You are creating a community for a social platform.
Community name: {name}
Topic: {topic}

Respond with ONLY a JSON object with these exact fields:
- display_name (string, human-readable name, max 50 chars)
- description (string, 1-2 sentences about the community)
- sidebar_text (string, 2-4 sentences for the sidebar)
- rules (array of 3-5 rule strings, short and direct)
- tags (array of 2-4 topic tag strings)

No other text. Just the JSON object."""


def lognormal_member_count() -> int:
    """Log-normal distribution skewed toward lower values (1k–2.5M)."""
    mu, sigma = 10.0, 2.5
    raw = int(math.exp(random.gauss(mu, sigma)))
    return max(1_000, min(2_500_000, raw))


def main():
    communities = []
    for seed in COMMUNITY_SEEDS:
        print(f"Generating r/{seed['name']}...", end=" ", flush=True)
        prompt = PROMPT_TEMPLATE.format(**seed)
        raw = llm_generate(prompt)
        data = extract_json(raw)

        if not data:
            print("FAILED (using defaults)")
            data = {
                "display_name": seed["name"],
                "description": seed["topic"][:200],
                "sidebar_text": seed["topic"][:200],
                "rules": ["Be respectful", "Stay on topic", "No spam"],
                "tags": [],
            }

        communities.append({
            "name": seed["name"],
            "display_name": str(data.get("display_name", seed["name"]))[:50],
            "description": str(data.get("description", "")),
            "sidebar_text": str(data.get("sidebar_text", "")),
            "rules": json.dumps(data.get("rules", [])),
            "tags": json.dumps(data.get("tags", [])),
            "icon_seed": secrets.token_hex(4),
            "banner_color": "#c4730a",
            "member_count": lognormal_member_count(),
            "post_style_prompt": seed.get("post_style_prompt"),
            "is_narrative": 1 if seed.get("is_narrative") else 0,
        })
        print("ok")

    print(f"\nInserting {len(communities)} communities...", end=" ", flush=True)
    resp = req.post(
        f"{APP_API_URL}/internal/communities/bulk",
        json={"communities": communities},
        headers=INTERNAL_HEADERS,
    )
    if resp.ok:
        data = resp.json()
        print(f"ok ({data.get('inserted', '?')} inserted)")
    else:
        print(f"FAILED: {resp.status_code} {resp.text}")


if __name__ == "__main__":
    main()
